config/routes.rb
V::Application.routes.draw do
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  resources :users, only: [:create, :new, :show]

  root to: 'home#index'
  get "home/index"
  resources :videos
  get "videos/subtitle/:id" => 'videos#subtitle'
  resources :categories

end

app/models/video.rb
class Video < ActiveRecord::Base
  has_and_belongs_to_many :categories
  belongs_to :group

  URL_PREFIX = Rails.application.config.base_url
  FILE_PREFIX = Rails.application.config.video_dir

  def next_video_in_group
    return nil unless group_id
    it_videos = group.videos.where(1).load.each
    loop do
      break if it_videos.next.id == id
    end

    next_video = nil
    begin
      next_video = it_videos.next
    rescue
      # ignored
    end
    next_video
  end

  def image_path
    path.sub(/\.[^.]*$/, '') + '.jpg'
  end

  def subtitle_path
    path.sub(/\.[^.]*$/, '') + '.srt'
  end

  def url
    URI.escape( URL_PREFIX + path )
  end

  def image_url
    URI.escape( URL_PREFIX + image_path )
  end

  def subtitle_url
    URI.escape( '/videos/subtitle/' + id.to_s )
  end

  def file
   FILE_PREFIX + path
  end

  def image_file
    FILE_PREFIX + image_path
  end

  def subtitle_file
    FILE_PREFIX + subtitle_path
  end

  def set_width_height
    self.width= 1280 #default values
    self.height= 720
    command = if RUBY_PLATFORM.include? 'mingw'
                '"C:\Program Files\ffmpeg\bin\ffprobe.exe" -show_streams -i ' + "\"#{file.encode('cp936')}\"" # chinese code page
              else
                "ffprobe -show_streams \"#{file}\""
              end
    data = `#{command}`.split "\n"
    data.each do |s|
      if s.start_with? 'width='
        self.width= s.sub('width=', '')
      end
      if s.start_with? 'height='
        self.height= s.sub('height=', '')
        return
      end
    end
  end

  def ass2srt
    ass_file = FILE_PREFIX + path.sub(/\.[^.]*$/, '') + '.ass'
    return unless File.exist? ass_file

    srt_file = File.open( subtitle_file, 'w' )
    index = -2
    File.open(ass_file, 'r').each_line do |line|
      index = -1 if line.start_with? '[Events]'
      next if index < -1
      if index > 0
        begin
        data = line.split ','
        start_time = '0' + data[1].sub('.', ',') + '0'
        end_time = '0' + data[2].sub('.', ',') + '0'
        text = data[-1]
        srt_file.write index.to_s + "\n"
        srt_file.write start_time + ' --> ' + end_time + "\n"
        srt_file.write text + "\n"
        rescue
          # ignored
        end
      end
      index += 1
    end
    srt_file.close

  end


end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authorize

  def show
    begin
      @video = Video.find params[:id]
      respond_to do |format|
        format.js {
          if is_mobile
            render inline: 'window.location = "' + @video.url + '"'
          else
            render
          end
        }
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end

  end

  def subtitle
    @video = Video.find params[:id]
    send_file File.join( Admin::ROOT, @video.subtitle_path)
  end

  def is_mobile
    request.headers[:HTTP_USER_AGENT].downcase.include? 'mobile'
  end


end

app/helpers/videos_helper.rb
module VideosHelper
  def image_url(video)
    if video.with_image
      video.image_url
    elsif video.group && video.group.image_url
      video.group.image_url
    else
      '/assets/cover.jpg'
    end
  end

end

app/views/videos/_list.html.erb
<div class="playlist">
  <% @video.group.videos.each do |video| %>
      <% if video.id == @video.id %>
        <div id="<%= video.id %>" class="current"><%= link_to video.name, video, remote: true %></div>
      <% else %>
        <div id="<%= video.id %>"><%= link_to video.name, video, remote: true %></div>
      <% end %>
  <% end %>
</div>
<script>
  var JPlaylist = $('.playlist');
  JPlaylist.animate({opacity: 0}, 1000);
  JPlaylist.hover(
          function(){$('.playlist').animate({opacity: 0.8},800);},
          function(){$('.playlist').animate({opacity: 0},800);}
  );

  <% next_video = @video.next_video_in_group %>
  <% if next_video %>
  var video = $('video')[0];
  video.addEventListener( "ended", function() {
      $.ajax({
          url: "<%= escape_javascript video_url next_video %>",
          dataType: 'script'
      });
  } );
  <% end %>
</script>

app/views/videos/_show.html.erb
<div id="player" class="player">
  <video width="<%= @video.width %>" height="<%= @video.height %>" preload="auto" controls>
     <source src="<%= @video.url %>" type='video/webm; codecs="vp8, vorbis"'/>
     <source src="<%= @video.url %>" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'/>
     <source src="<%= @video.url %>" type='video/ogg; codecs="theora, vorbis"'/>
  </video>
  <div id="notifications"></div>
  <div id="subtitler"></div>
  <% if ! @video.group_id.nil? %>
  <%= render 'list' %>
  <% end %>
</div>

<% if @video.with_subtitle? %>
    <script>
        $.get( '<%= @video.subtitle_url %>', function(data){
            var sub = new Subtitler();
            sub.setSubtitle(data);
            var video = $('video')[0];
            video.addEventListener( "timeupdate", function() {
                sub.move(video.currentTime);
            } );
        } );
    </script>
<% end %>

app/views/videos/show.html.erb
<div class="player">
    <div class="leanback-player-video">
      <video width="<%= @video.width %>" height="<%= @video.height %>" preload="auto" controls autoplay>
        <source src="<%= @video.url %>" type='video/webm; codecs="vp8, vorbis"'/>
        <source src="<%= @video.url %>" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'/>
        <source src="<%= @video.url %>" type='video/ogg; codecs="theora, vorbis"'/>
        <% if @video.with_subtitle? %>
            <track enabled="true" kind="subtitles" label="En/Ch" srclang="en/ch" type="text/x-srt" src="<%= @video.url_subtitle %>"></track>
        <% end %>
      </video>
    </div>
</div>


<%= stylesheet_link_tag 'leanbackPlayer.monochrome' %>
<%= javascript_include_tag 'leanbackPlayer' %>
<%= javascript_include_tag 'leanbackPlayer.en' %>

app/views/videos/show.js.erb
(function() {
    // handle original player if there's one
    try {
        $('#overlay').remove();
        $('video')[0].src = '';
        $('#player').remove();
    } catch(e) {

    }
    // handle click on overlay
    var removePlayer = function(){
            $('#overlay').fadeOut('slow', function(){$(this).remove();});
            $('#player').fadeOut('slow', function(){
                $('video')[0].src = '';
                $(this).remove();
            });
    };


    var JBody = $('body');

    JBody.append('<div id="overlay" class="overlay"></div>');

    JBody.append("<%= escape_javascript(render 'show') %>");

    var JPlayer = $('#player');
    var JVideo = $('video');
    var JOverlay = $('#overlay');
    var JSubDiv = $('#subtitler');

    var placePlayer = function() {
        var avaHeight = $(window).height();
        var avaWidth = $(window).width();
        var avaRatio = avaWidth / avaHeight;
        var oriWidth = <%= @video.width %>;
        var oriHeight = <%= @video.height %>;
        var width = oriWidth;
        var height = oriHeight;
        var oriRatio = oriWidth / oriHeight;
        if ( avaRatio > oriRatio ) {
            if ( avaHeight < oriHeight ) {
                height = avaHeight;
                width = oriWidth * ( avaHeight / oriHeight );
            }
        } else {
            if ( avaWidth < oriWidth ) {
                width = avaWidth;
                height = oriHeight * ( avaWidth / oriWidth )
            }
        }
        var top = ( avaHeight - height ) / 2 ;
        var left = ( avaWidth - width ) / 2 ;
        JPlayer.css( 'top', top );
        JPlayer.css( 'left', left );
        JVideo.css('width', width);
        JVideo.css('height', height);

        // subtitle

        if ( JSubDiv ) {
        JSubDiv.css( 'top', height - 80 );
        }

        // overlay
        JOverlay.height(Math.max( JBody.height(), avaHeight));
    };
    placePlayer();
    JPlayer.fadeIn('slow');
    $( window ).resize(function() {
        placePlayer();
    });

    var video =JVideo[0];
    video.volume = 0.8;
    video.play();
//    JVideo.click(function(e){ // no pause
//        e.preventDefault();
//    });

    JOverlay.fadeIn('slow');
    JOverlay.click(removePlayer);
    $(document).keyup(function(e) {
        if (e.keyCode == 27) removePlayer();
    });


})();