config/routes.rb
V::Application.routes.draw do
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  resources :users, only: [:create, :new, :show]

  root to: 'home#index'
  get "home/index"
  resources :videos
  get "videos/subtitle/:id" => 'videos#subtitle'
  resources :categories

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize
  
  def index
    @videos = []

    group_chosen = {}
    Video.all.to_a.shuffle!.each { |video|
      if video.group_id == nil
        @videos << video
      else
        if group_chosen.has_key? video.group_id
          next
        else
          @videos << video
          group_chosen[video.group_id] = true
        end
      end
    }
    @videos.shuffle!
    @categories = Category.all
    @category_id = 0
    @user = User.find_by_id session[:user_id]
  end
end

app/views/home/_category_nav.html.erb
<div class="pure-u-1">
    <div class="nav">
      <ul>
        <% class_names = (@category_id == 0 ? 'pure-button lss-button lss-button-blue' : 'pure-button lss-button lss-button-default')  %>
        <li> <%= link_to button_tag(type: 'button', class: class_names) {'Home'}, root_path %> </li>
        <% @categories.each do |category| %>
            <% class_names = (@category_id.to_i == category.id ? 'pure-button lss-button lss-button-blue' : 'pure-button lss-button lss-button-default')  %>
            <li> <%= link_to button_tag(type: 'button', class: class_names) {category.name}, category %> </li>
        <% end %>
        <% if @user %>
            <%= link_to button_tag(type: 'button', class: 'user pure-button lss-button lss-button-green') {@user.name}, user_path(@user.id) %>
        <% else %>
            <%= link_to button_tag(type: 'button', class: 'user pure-button lss-button lss-button-green') {'login'}, login_path %>
        <% end %>
      </ul>

    </div>
</div>

app/views/home/_video_list.html.erb
<div id="video-list" class="pure-u-1">
    <% @videos.each_with_index do |video, i| %>
        <div data-seq="<%= i + 1 %>" class="unit">
          <a href="/videos/<%= video.id %>" data-remote="true">
            <img class="small-cover" src="<%= image_url(video) %>">
          </a>
          <div class="info">
            <%= video.name %>
          </div>
        </div>
    <% end %>
</div>

app/views/home/index.html.erb
<%= render 'home/category_nav' %>

<%= render 'home/video_list' %>